[workspace]
workspace.resolver = "2"
members = ["crates/*"]
default-members = ["crates/server"]

[workspace.dependancies]


[profile.dev]
incremental = true
debug = true

[profile.release]
incremental = true
opt-level = 3
debug = true
